export const NAVIGATE = 'NAVIGATE';
export const BACK_SCREEN = 'BACK_SCREEN';

export const START_LOADING_SPIN = 'START_LOADING_SPIN';
export const STOP_LOADING_SPIN = 'STOP_LOADING_SPIN';

export const UPDATE_ACCESS_TOKEN = 'UPDATE_ACCESS_TOKEN';
export const UPDATE_ACTIVE_USER = 'UPDATE_ACTIVE_USER';
